apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: notes-app
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}
