apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
  namespace: notes-app
data:
  init.sql: |
    CREATE TABLE users (
        user_id SERIAL PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL
    );
    CREATE TABLE notes (
        note_id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL,
        note TEXT,
        created_at TIMESTAMP,
        CONSTRAINT fk_user
            FOREIGN KEY(user_id) 
            REFERENCES users(user_id)
            ON DELETE CASCADE
    );
